# -*- coding: utf-8 -*-
{
    'name': '工作流引擎',
    'summary': '工作流应用,提供丰富的流程节点管理',
    'author': 'Jinjie',
    'website': '',
    'category': '公共/公共',
    'depends' : ['base', 'web', 'hr', 'mail'],
    'version': '1.0',
    'data': [
        'security/security_chown.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'data/message.xml',
        'data/model_category.xml',
        # 'data/report_paperformat_data.xml',
        'views/res_users_views.xml',
        # 'views/todo_all_view.xml',
        'views/ir_process_view.xml',
        'views/workflow_role_view.xml',
        'views/hd_workflow_view.xml',
        'views/personnel_process_record_view.xml',
        'views/basic_attachment_form_view.xml',
        'views/approval_check_user_wizard.xml',
        'views/hd_chown.xml',
        'wizard/chown_ban.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
            'web.assets_backend': [
                'hd_workflow/static/src/model/*.js',
                'hd_workflow/static/src/components/*/*.js',
                'hd_workflow/static/src/components/*/*.scss',
                'hd_workflow/static/src/components/*/*.xml',
                'hd_workflow/static/src/models/*.js',
                'hd_workflow/static/src/services/*.js',
                # 'hd_workflow/static/src/views/*/*.js',
                # 'hd_workflow/static/src/xml/rp_curd.xml',
            ]
    },
    'license': 'LGPL-3',
}
